
import React, { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Check, FileText, Send, Shield } from 'lucide-react';
import { toast } from 'sonner';
import { submitReportToOfficer } from '@/services/reportServices';
import { saveReportPdf } from '@/services/reportPdfService';
import { supabase } from '@/integrations/supabase/client';
import jsPDF from 'jspdf';

const SelfReportForm = () => {
  const { user } = useAuth();
  const [description, setDescription] = useState('');
  const [isAnonymous, setIsAnonymous] = useState(false);
  const [isConfidential, setIsConfidential] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!description.trim()) {
      toast.error("Please provide a description of what happened");
      return;
    }

    setIsSubmitting(true);

    try {
      // Create a new report in the database
      const { data: reportData, error } = await supabase
        .from('crime_reports')
        .insert([
          {
            user_id: user?.id,
            title: 'Self Report',
            description: description,
            is_anonymous: isAnonymous,
            status: 'draft',
            // Add a tag for confidential reports
            officer_notes: isConfidential ? 'CONFIDENTIAL: Keep private' : '',
          },
        ])
        .select()
        .single();

      if (error) throw error;

      // Generate PDF report
      await generatePdfReport(reportData);

      // Submit report to officer
      await submitReportToOfficer(reportData.id);

      toast.success('Your report has been submitted successfully');
      setIsSuccess(true);
      
      // Reset form after success
      setTimeout(() => {
        setDescription('');
        setIsAnonymous(false);
        setIsConfidential(false);
        setIsSuccess(false);
      }, 3000);
    } catch (error) {
      console.error('Error submitting report:', error);
      toast.error('Failed to submit report. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const generatePdfReport = async (reportData) => {
    const pdf = new jsPDF();
    const dateFormatted = new Date().toLocaleString();

    // Add title
    pdf.setFontSize(20);
    pdf.text('Self Report', 105, 20, { align: 'center' });
    
    // Add report metadata
    pdf.setFontSize(12);
    pdf.text(`Report ID: ${reportData.id}`, 20, 40);
    pdf.text(`Date: ${dateFormatted}`, 20, 50);
    pdf.text(`Anonymous: ${isAnonymous ? 'Yes' : 'No'}`, 20, 60);
    pdf.text(`Confidential: ${isConfidential ? 'Yes' : 'No'}`, 20, 70);
    
    // Add report description
    pdf.setFontSize(14);
    pdf.text('Description:', 20, 90);
    
    // Handle text wrapping for description
    const textLines = pdf.splitTextToSize(description, 170);
    pdf.setFontSize(11);
    pdf.text(textLines, 20, 100);
    
    // Add watermark/footer
    pdf.setFontSize(10);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by Shield App', 105, 280, { align: 'center' });
    
    // Save PDF to blob
    const pdfBlob = pdf.output('blob');
    
    // Upload PDF to Supabase
    await saveReportPdf(
      reportData.id,
      pdfBlob,
      `self_report_${new Date().getTime()}.pdf`,
      true
    );
  };

  if (!user) {
    return (
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Self Report</CardTitle>
          <CardDescription>
            Please sign in to submit a report
          </CardDescription>
        </CardHeader>
      </Card>
    );
  }

  return (
    <Card className="w-full bg-white shadow-lg border-none">
      <CardHeader className="bg-shield-blue/5 rounded-t-lg">
        <CardTitle className="flex items-center gap-2 text-shield-blue">
          <Shield className="h-5 w-5" />
          Self Report Form
        </CardTitle>
        <CardDescription>
          Describe what happened to you, even without photos or videos
        </CardDescription>
      </CardHeader>
      <CardContent className="pt-6">
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="space-y-2">
            <label htmlFor="report-description" className="text-sm font-medium">
              Please describe what happened
            </label>
            <Textarea
              id="report-description"
              placeholder="Describe in detail what happened, when, where, and any other relevant information..."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="min-h-[200px] resize-y"
              disabled={isSubmitting || isSuccess}
            />
          </div>
          
          <div className="space-y-4">
            <div className="flex items-center justify-between border-t border-gray-100 pt-4">
              <div className="space-y-0.5">
                <h4 className="text-sm font-medium">Submit Anonymously</h4>
                <p className="text-xs text-muted-foreground">
                  Your identity will not be revealed
                </p>
              </div>
              <Switch 
                checked={isAnonymous} 
                onCheckedChange={setIsAnonymous}
                disabled={isSubmitting || isSuccess}
              />
            </div>
            
            <div className="flex items-center justify-between border-t border-gray-100 pt-4">
              <div className="space-y-0.5">
                <h4 className="text-sm font-medium">Confidential Report</h4>
                <p className="text-xs text-muted-foreground">
                  Request that your data is kept confidential
                </p>
              </div>
              <Switch 
                checked={isConfidential} 
                onCheckedChange={setIsConfidential}
                disabled={isSubmitting || isSuccess}
              />
            </div>
          </div>
          
          <Button 
            type="submit" 
            className="w-full bg-shield-blue hover:bg-shield-blue/90"
            disabled={isSubmitting || isSuccess}
          >
            {isSubmitting ? (
              <>Processing...</>
            ) : isSuccess ? (
              <><Check className="mr-2 h-4 w-4" /> Submitted Successfully</>
            ) : (
              <><Send className="mr-2 h-4 w-4" /> Submit Report</>
            )}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
};

export default SelfReportForm;
